[phases.setup]
nixPkgs = ["nodejs_20", "python3", "ffmpeg"]

[phases.install]
cmds = [
  "npm install",
  "pip3 install --no-cache-dir yt-dlp"
]

[start]
cmd = "node src/server.js"

[variables]
NODE_ENV = "production"

